apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    extensionProviders:
    - name: "opa"
      envoyExtAuthzHttp:
        service: "opa.default.svc.cluster.local"
        port: "8181"
        # Envoy ext-authz는 기본적으로 / 체크 엔드포인트를 호출하므로
        # OPA의 데이터 경로(/v1/data/...)로 맞춰주기 위해 prefix를 지정
        pathPrefix: /v1/data
        includeRequestHeadersInCheck: ["role"]
    - envoyOtelAls:
        port: 4317
        service: opentelemetry-collector.observability.svc.cluster.local
      name: otel
    - name: skywalking
      skywalking:
        port: 11800
        service: tracing.istio-system.svc.cluster.local
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.observability.svc.cluster.local
    - name: jaeger
      opentelemetry:
        port: 4317
        service: jaeger-collector.istio-system.svc.cluster.local
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-26T15:19:03Z"
  labels:
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.28.3
    helm.sh/chart: istiod-1.28.3
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.28.3
    release: istio
  name: istio
  namespace: istio-system
  resourceVersion: "6068"
  uid: 7177a060-3147-4cff-a309-7ed6bcb2c355
